export const FETCH_PRODCS_BY_SEARCH_INPUT = "FETCH_PRODCS_BY_SEARCH_INPUT";
export const FETCH_PRODCS_BY_CATEGORY = "FETCH_PRODCS_BY_CATEGORY";
export const FETCH_PRODCS_BY_PRICE = "FETCH_PRODCS_BY_PRICE";
export const SWITCH_LANGUAGE = "SWITCH_LANGUAGE";
export const FETCH_CART = "FETCH_CART";
export const ADD_TO_CART = "ADD_TO_CART";
export const SWITCH_BUTTON = "SWITCH_BUTTON";
export const FETCH_ALL_PRODUCTS = "FETCH_ALL_PRODUCTS";
